In [1]:
import numpy as np
import matplotlib.pyplot as plt

stock_list=[3.5,5,2,8,4.2]

In [17]:
stock_list=[3.5,5,2,8,4.2]
returns = np.array(stock_list)
print returns
print np.log(returns)

[ 3.5  5.   2.   8.   4.2]
[ 1.25276297  1.60943791  0.69314718  2.07944154  1.43508453]


In [24]:
N=10
assets = np.zeros((N,100))
returns = np.zeros((N,100))

R_1 = np.random.normal(1.01,0.03, 100)
returns[0] = R_1
assets[0] = np.cumprod(R_1)

print returns

[[ 0.99605973  0.96669122  1.05810701  0.9802302   0.95010265  1.01306331
   1.0449758   1.01493086  0.98687309  1.00730237  1.04717663  0.98885511
   1.0794191   0.95873606  1.05547831  1.04328735  1.04046207  1.02279622
   0.99959635  0.98738549  1.00251694  0.98908921  1.00226868  1.02146866
   1.03034618  1.01151163  1.03022424  0.99817867  1.0220668   1.0121154
   1.01521977  0.96871482  0.97657027  0.98750836  1.03339686  1.04550445
   1.03213139  1.0375099   1.01731312  1.0260015   0.96251022  1.03274076
   1.05183247  1.02004651  0.9676301   1.03713633  1.04134546  0.99624058
   0.99780429  0.97742904  1.03712573  0.99539484  1.05549001  0.99737682
   1.05216541  0.96508308  1.0422794   1.02918894  0.9503824   1.03902665
   1.01674205  1.00097754  0.96100452  0.98526337  1.02009219  1.01235653
   0.98990112  1.05309855  1.03009527  1.02386085  0.93526461  1.0262993
   0.98661279  1.01114009  1.00931545  1.01109136  1.06229373  0.96688856
   0.9567518   1.03519603  1.02625311  1

[ 1.25276297  1.60943791  0.69314718  2.07944154  1.43508453]
